// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ2HiRgfGhFUsO8Xwa7jkorCRrMNbolCw',
    appId: '1:1088594429705:web:636fe2955d0146616335d8',
    messagingSenderId: '1088594429705',
    projectId: 'tccmentoria-11d4a',
    authDomain: 'tccmentoria-11d4a.firebaseapp.com',
    storageBucket: 'tccmentoria-11d4a.appspot.com',
    measurementId: 'G-5HD9R1G6T6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAy0RTY9bfXLDPFYhI8C7lWYxgR-ZpXSw',
    appId: '1:1088594429705:android:c4dcd93d67debdab6335d8',
    messagingSenderId: '1088594429705',
    projectId: 'tccmentoria-11d4a',
    storageBucket: 'tccmentoria-11d4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0YuOCqWAMMW8_9IM9IEvSzIabh1BAX9M',
    appId: '1:1088594429705:ios:d42ee8f19f6b2c246335d8',
    messagingSenderId: '1088594429705',
    projectId: 'tccmentoria-11d4a',
    storageBucket: 'tccmentoria-11d4a.appspot.com',
    iosClientId:
        '1088594429705-v9871ifs1thctbcashadjfnk4bi79io3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tccfacul',
  );
}
